# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class LocationEnum(str, Enum):
    """
    Where the household is located
    """

    """
    allowed enum values
    """
    VICTORIA = 'VICTORIA'
    NEW_SOUTH_WALES = 'NEW_SOUTH_WALES'
    NORTHERN_TERRITORY = 'NORTHERN_TERRITORY'
    AUSTRALIAN_CAPITAL_TERRITORY = 'AUSTRALIAN_CAPITAL_TERRITORY'
    TASMANIA = 'TASMANIA'
    WESTERN_AUSTRALIA = 'WESTERN_AUSTRALIA'
    SOUTH_AUSTRALIA = 'SOUTH_AUSTRALIA'
    QUEENSLAND = 'QUEENSLAND'

    @classmethod
    def from_json(cls, json_str: str) -> LocationEnum:
        """Create an instance of LocationEnum from a JSON string"""
        return LocationEnum(json.loads(json_str))


